// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TastivalFood.Infrastructure.Persistence;

#nullable disable

namespace TastivalFood.Infrastructure.Migrations
{
    [DbContext(typeof(TastivalFoodDbContext))]
    [Migration("20260608105115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergyMenuItem", b =>
                {
                    b.Property<Guid>("AllergiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuItemsId")
                        .HasColumnType("uuid");

                    b.HasKey("AllergiesId", "MenuItemsId");

                    b.HasIndex("MenuItemsId");

                    b.ToTable("MenuItemAllergies", (string)null);
                });

            modelBuilder.Entity("IngredientMenuItem", b =>
                {
                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuItemsId")
                        .HasColumnType("uuid");

                    b.HasKey("IngredientsId", "MenuItemsId");

                    b.HasIndex("MenuItemsId");

                    b.ToTable("MenuItemIngredients", (string)null);
                });

            modelBuilder.Entity("RestaurantTypeUser", b =>
                {
                    b.Property<Guid>("RestaurantTypesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RestaurantTypesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRestaurantTypes", (string)null);
                });

            modelBuilder.Entity("TastivalFood.Domain.Entities.Allergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3000001-0000-4000-8000-000000000001"),
                            Description = "Gluten allergy",
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0000-4000-8000-000000000002"),
                            Description = "Milk allergy",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0000-4000-8000-000000000003"),
                            Description = "Peanut allergy",
                            Name = "Peanut"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0000-4000-8000-000000000004"),
                            Description = "Soy allergy",
                            Name = "Soy"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0000-4000-8000-000000000005"),
                            Description = "Egg allergy",
                            Name = "Egg"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0000-4000-8000-000000000006"),
                            Description = "Fish allergy",
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0000-4000-8000-000000000007"),
                            Description = "Shellfish allergy",
                            Name = "Shellfish"
                        });
                });

            modelBuilder.Entity("TastivalFood.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("TastivalFood.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHalal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PopularityScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RestaurantOwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.HasIndex("RestaurantOwnerId");

                    b.ToTable("MenuItems", t =>
                        {
                            t.HasCheckConstraint("CK_MenuItems_Calories", "Calories >= 0");

                            t.HasCheckConstraint("CK_MenuItems_PopularityScore", "PopularityScore >= 0 AND PopularityScore <= 5");
                        });
                });

            modelBuilder.Entity("TastivalFood.Domain.Entities.Origin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Origins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000001"),
                            CountryName = "Iran"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000002"),
                            CountryName = "Italy"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000003"),
                            CountryName = "France"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000004"),
                            CountryName = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000005"),
                            CountryName = "Japan"
                        });
                });

            modelBuilder.Entity("TastivalFood.Domain.Entities.RestaurantType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RestaurantTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000001"),
                            Name = "Persian"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000002"),
                            Name = "Italian"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000003"),
                            Name = "Cafe"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000004"),
                            Name = "FastFood"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000005"),
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000006"),
                            Name = "Seafood"
                        });
                });

            modelBuilder.Entity("TastivalFood.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AllergyMenuItem", b =>
                {
                    b.HasOne("TastivalFood.Domain.Entities.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TastivalFood.Domain.Entities.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IngredientMenuItem", b =>
                {
                    b.HasOne("TastivalFood.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TastivalFood.Domain.Entities.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantTypeUser", b =>
                {
                    b.HasOne("TastivalFood.Domain.Entities.RestaurantType", null)
                        .WithMany()
                        .HasForeignKey("RestaurantTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TastivalFood.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TastivalFood.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("TastivalFood.Domain.Entities.Origin", "Origin")
                        .WithMany("MenuItems")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TastivalFood.Domain.Entities.User", "RestaurantOwner")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");

                    b.Navigation("RestaurantOwner");
                });

            modelBuilder.Entity("TastivalFood.Domain.Entities.Origin", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("TastivalFood.Domain.Entities.User", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
